### ISSUE TITLE
  cannot open compressed file 'precalculated_windows/QNDAseq_bins50.RData', probable reason 'No such file or directory'

### ISSUE THREAD

**Issue by Urja25** [sdentro/qdnaseq_pipeline#1]
Hi, I am trying to run the modified qdnaseq_pipeline and run into the following error:
`cannot open compressed file 'precalculated_windows/QNDAseq_bins50.RData', probable reason 'No such file or directory'` 

Where exactly is this file present?

**Comment by sdentro** [comment]
These can be generated with QDNAseq. Here's an example on how to do this for mouse data. This requires the `bigWigAverageOverBed` tool to be in the same directory where this code is run

```
binSize = 50
library(QDNAseq)
library(Biobase)
library(BSgenome.Mmusculus.UCSC.mm10)
bins <- createBins(bsgenome=BSgenome.Mmusculus.UCSC.mm10, binSize=binSize)
bins$mappability <- calculateMappability(bins,
                                         bigWigFile=mappability_file_mm10,
                                         bigWigAverageOverBed=file.path(getwd(),"bigWigAverageOverBed"),
                                         chrPrefix="")
save.image(file=file.path(paste0("QNDAseq_bins", binSize, ".RData")))
```

More details can be found in the QDNAseq documentation in section 4 [here](https://bioconductor.org/packages/devel/bioc/vignettes/QDNAseq/inst/doc/QDNAseq.pdf)
